version: "3.8"
services:
  abala:
    build:
      dockerfile: Dockerfile
    ports:
      - "80"
  db:
    image: mysql
    build:
      context: sql
    environment:
      MYSQL_ROOT_PASSWORD: gropd
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1